# Generated by Django 3.1.3 on 2020-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201115_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='age',
        ),
        migrations.AddField(
            model_name='image',
            name='country',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
