# Generated by Django 3.1.3 on 2020-11-26 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201115_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image2',
            new_name='reference_image',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image1',
            new_name='source_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='age',
        ),
        migrations.RemoveField(
            model_name='image',
            name='country',
        ),
    ]
